### ISSUE TITLE
Installation with llvm from macports fails

### ISSUE THREAD

**Issue by VictorEijkhout** [hdoc/hdoc#1]
I have llvm installed (OS X 10.15) but meson still reports not finding llvm. Probably because llvm-config has a non-standard name.

```
llvm-config-mp-11     llvm-config-mp-3.5    llvm-config-mp-9.0    llvm-config-mp-devel
```

Is there a setting to specify this?

**Comment by hdoc** [comment]
hdoc doesn't officially support macOS yet. We have internal builds running, but they don't work perfectly. In particular, they have problems locating system headers. We recommend using Linux, which undergoes strict testing and has precompiled binaries available at hdoc.io.

However, I'll try to offer some help.

Meson not finding LLVM is a question for the meson folks, I assume they hardcode the name of llvm-config and don't look for these packaging-dependent names.

I see two ways forward:
1. Create a symlink with the name `llvm-config` point it to `llvm-config-mp-11`, and hope that works
    - We received a report of hdoc not building on LLVM/Clang 11 though, so you may want to try LLVM/Clang 10 if that doesn't work
2. Get a Linux machine or VM and try there. Builds should work out of the box assuming dependencies are installed correctly, and there are precompiled binaries available. There's also the Nix configuration which is guaranteed to work on Linux.
