### ISSUE TITLE
Provide Binaries

### ISSUE THREAD

**Issue by dufferzafar** [hdoc/hdoc#13]
I really want to try out hdoc on my code, and I think providing binaries would be a great way of reducing the friction.

**Comment by hdoc** [comment]
Hello, we offer precompiled fully-static binaries on [hdoc.io](https://hdoc.io/) when you create an account. These binaries come with the capability of uploading your documentation to our hosting service, [docs.hdoc.io](https://docs.hdoc.io/), all for free.

We recently also added the capability of building your documentation directly from GitHub CI using our GitHub Action (link to [blog post](https://hdoc.io/blog/hdoc-github-actions-beta/), link to [GitHub repo](https://github.com/hdoc/hdoc-github-action)). This avoids having to download the binary and run it locally.

**Comment by dufferzafar** [comment]
Does this mean we can't work with hdoc without an API key? I don't want to upload my docs to hdoc, just want to keep them locally.

**Comment by hdoc** [comment]
I apologize for the late response. hdoc still works without an API key, however you have to compile hdoc yourself to do that. There are [instructions in the README](https://github.com/hdoc/hdoc#quick-start) file for how to do this.
