### ISSUE TITLE
Ability to hide or change giant "hdoc" title in the sidebar

### ISSUE THREAD

**Issue by jtbandes** [hdoc/hdoc#19]
Another change that I keep in a [hdoc patch](https://github.com/foxglove/mcap/blob/a85bd00295255b134f3083efbc5d2274294a83df/cpp/hdoc.patch) is to remove this large "hdoc" link from the sidebar:

<img width="461" alt="image" src="https://user-images.githubusercontent.com/14237/180505785-d7643a47-e14e-4009-8b87-8095da6308c4.png">

I'm not against having a link back to hdoc.io to make the tool discoverable (and there already is one in the footer), but it doesn't need to be the **largest** link on the page and prominently displayed above the title of the actual project being documented. 😄

**Comment by hdoc** [comment]
This will be fixed in the next release, likely by moving the link to hdoc to a less visually invasive link/text at the bottom of the sidebar.

**Comment by ConorWilliams** [comment]
> This will be fixed in the next release, likely by moving the link to hdoc to a less visually invasive link/text at the bottom of the sidebar.

Fantatsic, awaiting this feature as well :)

**Comment by hdoc** [comment]
Hello @jtbandes, your suggestion has been implemented in hdoc 1.3.1 which we just released. We have credited you in the release notes, which can be found here: https://hdoc.io/release-notes/#version-1-3-1-29-september-2022. Thank you as always!

![no-more-giant-link](https://user-images.githubusercontent.com/68132204/193169946-93f05044-e7f5-4959-ba13-3e52c6badd74.png)
