### ISSUE TITLE
Way to add examples to documentation

### ISSUE THREAD

**Issue by ConorWilliams** [hdoc/hdoc#20]
Feature request: 

The only thing stopping me from fully adopting hdoc is the inability to add nicely formatted code examples. 
Ideally this would take the form of something like Doxygens:
```
\code{.cpp}
[[magic import example.cpp]]
\endcode 
```

**Comment by hdoc** [comment]
This is something that we've been meaning to add for a while. The likely format this will take will be similar to Rust's documentation tool, i.e.

```
/// Calculate Euclidean distance in $\R^2$.
/// Corresponds to the following formula:
/// $$ d(x,y) = \sqrt{(x_2-x_1)^2 + (y_2-y_1)^2} $$
/// @param x1 $\sqrt{x_1}$
/// @param y1 $\sqrt{y_1}$
/// @param x2 $\sqrt{x_2}$
/// @param y2 $\sqrt{y_2}$
/// @returns the result of $$ \sqrt{(x_2-x_1)^2 + (y_2-y_1)^2} $$
///
/// Usage example:
///
/// ```
///     const double res = calculate2DEuclideanDistance(0.0, 1.0, 1.0, 0.0);
/// ```
double calculate2DEuclideanDistance(const double x1, const double y1, const double x2, const double y2);
```

Importing files within these blocks as you have in your example is unlikely to be added.

**Comment by ConorWilliams** [comment]
> Importing files within these blocks as you have in your example is unlikely to be added.

That is a shame as it would enable the examples to be checked by the compiler

**Comment by hdoc** [comment]
I apologize for the late reply. Having examples that can be checked by the compiler is in-scope for hdoc, but I don't think we'll have a magic import function similar to what you had in the original comment. Inline code, like what rustdoc does or what I have in my example above, is more in line with what we have in mind.

We would be willing to look at PRs for such a feature. Additionally, if you work at an organization that needs this feature, please reach out to us at [contact@hdoc.io](mailto:contact@hdoc.io) and we can work out an agreement to fast-track development on this.

In any case, this is something that we plan to add to hdoc several releases from now, which is to say it's on the roadmap but not actively being worked on. Closing this issue for now and we will update it when we get around to adding this feature.
