### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by aydwi** [hdoc/hdoc#21]
The build system does not support compiling to UNIX like OSs like macOS. The prebuilt binaries are also only distributed for Linux. This makes working with hdoc impossible on macOS.

Are there plans to support it?

**Comment by hdoc** [comment]
hdoc compiles and runs on macOS using the Nix Flake supplied in this repository. We don't officially support it, but we do have internal builds that run macOS, and we've had the capability for years. We have plans to add macOS support eventually.

In the meantime, I would encourage you to use the Nix Flake to build hdoc. The instructions for Linux in the README should also work on macOS, assuming you're using the Flake to set up your development environment. I believe the only change that needs to be made is substituting all instances of `x86_64-linux` for `aarch64-darwin` (for Apple Silicon Macs) or `x86_64-darwin` (for Intel-based Macs) in `flake.nix`.
