### ISSUE TITLE
Tips on web output (JSON)

### ISSUE THREAD

**Issue by hinell** [hdoc/hdoc#23]
Modern javascript web apps are better to handle JSON data.

Documentation generator may simply output `.json` file with all symbols & descriptions and feed it into a web application (based on React/Angular/AnyOtherFramework) which finally may display however it wants. It's much better approach that generating html string.

It comes at disadvantage of having to use JavaScript though...

**Comment by hdoc** [comment]
Hello, thank you for the suggestion. While there are some advantages to the approach you suggested, we do not plan on adopting it. We prioritize simplicity in hdoc's output, and the simplicity of hosting static HTML files cannot be beat. There is room for improvement in how hdoc generates the HTML at runtime, but we do not plan on moving away from the static HTML output any time soon.
