### ISSUE TITLE
Search loading spinner is invisible in light color scheme

### ISSUE THREAD

**Issue by jtbandes** [hdoc/hdoc#24]
Environment: Safari 16.0, macOS 12.5.1

Dark theme:
<img width="1044" alt="Screen Shot 2022-09-30 at 11 14 37 AM" src="https://user-images.githubusercontent.com/14237/193332018-27f27d8f-ffa6-4ce2-ab8e-8b559d367701.png">

Light theme:
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/14237/193332157-c14f282a-cdd7-4533-a365-5becbf2f05cb.png">

Light theme (with text selected for contrast):
<img width="1131" alt="Screen Shot 2022-09-30 at 11 14 54 AM" src="https://user-images.githubusercontent.com/14237/193332126-b44f29bd-d9f7-4610-a6cb-2d3573a10320.png">

**Comment by hdoc** [comment]
Thank you, clearly we all use dark mode on our systems and didn't notice this. We will hotfix this.

**Comment by hdoc** [comment]
@jtbandes, this was fixed in hdoc 1.3.2 which was just released. We have credited you in the release notes, which can be found here: https://hdoc.io/release-notes/#version-1-3-2-30-september-2022. Thank you!
