### ISSUE TITLE
Macros

### ISSUE THREAD

**Issue by strager** [hdoc/hdoc#29]
It looks like hdoc doesn't show me any macros. It only shows me classes, functions, enums, and namespaces. I'd like to see my macros listed, searchable, and documented.

I use macros for #include guards. I do *not* want those macros to be listed by hdoc (because that would be super noisy and annoying).

I have some macros which are only defined in certain .cpp files ([example](https://github.com/quick-lint/quick-lint-js/blob/4f4dd179a484a6bb06adfe2576b8fae02742e088/src/quick-lint-js/fe/lex.cpp#L37), [example](https://github.com/quick-lint/quick-lint-js/blob/4f4dd179a484a6bb06adfe2576b8fae02742e088/src/quick-lint-js/fe/lex.cpp#L2321-L2323)). I am unsure if I those macros to be listed by hdoc.

**Comment by hdoc** [comment]
Thank you for the suggestion. Macros are on our roadmap but we currently do not support them. We would be happy to work with you on getting a PR merged in for this feature if you're interested.
