### ISSUE TITLE
Global variables

### ISSUE THREAD

**Issue by strager** [hdoc/hdoc#30]
It looks like hdoc doesn't show me any global variables. It only shows me classes, functions, enums, and namespaces. I'd like to see my globals listed, searchable, and documented.

I have some file-scoped global variables ([example](https://github.com/quick-lint/quick-lint-js/blob/4f4dd179a484a6bb06adfe2576b8fae02742e088/src/quick-lint-js/io/output-stream.cpp#L16-L18), [example](https://github.com/quick-lint/quick-lint-js/blob/4f4dd179a484a6bb06adfe2576b8fae02742e088/src/quick-lint-js/fe/lex.cpp#L83-L90)). I do not want those variables to be listed by hdoc (because that would be noisy, and possibly confusing because of name collisions).

**Comment by hdoc** [comment]
Thank you for the suggestion. 

Global variables are tricky. Your examples are simple and I could see global variable support in hdoc supporting simple declarations like the ones you linked. However, global variables can become large, difficult to parse, and difficult to present logically to the documentation consumer. 

One example that comes to mind is that of a finite state machine state transition table which could be implemented as a global array of structs. How would we go about parsing this information and presenting it within hdoc in a logical and clear manner? Take the whole declaration, format it so it looks pretty, and print it out in the HTML? Or do we draw the line at integer global variables and say that anything more complex is unsupported? If we do the former, we commit ourselves to supporting any number of obscure edge cases (for seemingly little benefit). If we do the latter, users may be confused when some of their global variables are documented but others are not.

For what it's worth, I did a quick survey of other documentation tools from C++ and other languages and found that some popular documentation tools do not support documenting global variables. For example, rustdoc, sphinx, and even Doxygen. None of them seem to easily support global variables (though I'm happy to be proven wrong). Perhaps that is a sign that this is not worth pursing.

In any case, we are open to concrete proposals on how to integrate global variables within hdoc, and even more open to PRs that implement such a feature, but I cannot promise we will implement them before these questions are resolved.

**Comment by strager** [comment]
> Take the whole declaration, format it so it looks pretty, and print it out in the HTML?

For your example, I don't think the global variable's initial value is important to document. (The link to the code is enough.) What I want to see in hdoc is the variable's name and declared type (and modifiers like `thread_local` or `constexpr`).

**Comment by hdoc** [comment]
We'll consider implementing this in a future version of hdoc. If you work at a company that needs this feature, please reach out to us at [contact@hdoc.io](mailto:contact@hdoc.io) and we can prioritize this work.
