### ISSUE TITLE
Omit private parts of a class (optionally?)

### ISSUE THREAD

**Issue by danakj** [hdoc/hdoc#35]
The Array class: https://github.com/chromium/subspace/blob/main/containers/array.h#L55-L187
Has 3 private enums and constructors: https://github.com/chromium/subspace/blob/main/containers/array.h#L148-L161

These are implementation details and do not need to be part of the API documentation.

The documentation for them is generated, such as
`Array::WithValue` here: https://docs.hdoc.io/danakj/subspace/e08FDD64E8BCF8383.html
`Array` constructor here: https://docs.hdoc.io/danakj/subspace/r3AD4D4163C31005F.html#2F7F3841EEE6B9CB

**Comment by hdoc** [comment]
Hello, there is an existing configuration file option that should omit private member variables from being indexed and appearing in the HTML output. It is `ignore.ignore_private_members`. Please give it a try on your codebase and let us know if it solves the issue.

Some more documentation on this option can be found at the link below.
https://hdoc.io/docs/reference/config-file-reference/#ignore-private-members

One caveat to this is that nested types (such as the enum `WithValue` in your code) will still be indexed and appear under the "Enums" section of the HTML despite `ignore_private_members` being true. However, they won't appear in the member variables list of `Array`. This is a bug and we will fix it by ignoring nested types that are private when `ignore_private_members` is true.

Feel free to ask any other questions that may come up.

**Comment by danakj** [comment]
Thanks, this worked in the way you suggested it would.

https://docs.hdoc.io/danakj/subspace/eE44B2B0FBC74B51B.html exists but it's not appearing in https://docs.hdoc.io/danakj/subspace/r3AD4D4163C31005F.html anymore.
