### ISSUE TITLE
Incorrect/Weird display of function

### ISSUE THREAD

**Issue by Wmbat** [hdoc/hdoc#4]
When I declare a function as a return type like so 
```cpp
constexpr auto borrow() const& noexcept -> const value_type&;
```
hdoc displays it like so https://imgur.com/a/A17UJ6g

It seems to split the `const&` specifier on a member function and split it in 2 parts. Not sure why it happens. It's not a big bug, but i thought it was worth reporting

**Comment by hdoc** [comment]
Hello, thanks for the issue report!

I think this is purely a cosmetic bug. Declarations are broken into multiple lines by clang-format if they [exceed 50 chars in length](https://github.com/hdoc/hdoc/blob/master/src/serde/HTMLWriter.hpp#L40). Without this, declarations can start exceeding page width and the generated documentation looks wonky.

It occasionally produces ugly results (as your example shows), so if you have any suggestions on how to improve it or a PR I'm all ears.

**Comment by Wmbat** [comment]
Well, it does that same thing, where it removes the `&&` or `&` from the `const` in member functions. I it does that in all the functions in my library. which could cause problems when looking at the documentation. This function
```cpp
constexpr auto take() && noexcept -> value_type;
```
is essentially turned into this 
```cpp
constexpr auto take() -> reglisse::left::value_type && noexcept;
``` 
in the [documentation](https://imgur.com/a/hCTdMIb), So, if someone looked at the docs, they'd think the function is returning an rvalue instead of only being invocable in rvalues. That `&&` & `noexept` is not placed correctly and it could be problematic. As to how to fix it, i'm not sure since i'm not familiar with Clang tools and the codebase

**Comment by hdoc** [comment]
My mistake, I misinterpreted your original comment. Yes, this is a bug in how hdoc prints out function declarations. Thank you for the test case, we'll get this fixed in the next release.

**Comment by hdoc** [comment]
The fix for this is in and it should be out mid-next week. Thank you for the test cases, this was certainly worth reporting! Please let us know if you find any more bugs.

**Comment by hdoc** [comment]
Newest release with the fix is up: https://github.com/hdoc/hdoc/releases/tag/1.2.0. Thanks again for the report.
