### ISSUE TITLE
Compiler Error on MacOS

### ISSUE THREAD

**Issue by grhawk** [hdoc/hdoc#42]
Hello, 

First of all, I genuinely think your product is beautiful! Thank you very much for working on it!

Now, about the issue.

I wanted to compile the code on my Mac (Intel) but unfortunately, I got some error from the compilers (I tried clang14 and gcc13). The errors seems to be related, somehow, to your code (release 1.4.1). However, I am not an expert and I did not dig too deep, so I would expect that the errors are somehow due to some issue with my setup. 

I did not find any specific instruction for MacOS so I tried to fill the holes. Once I would be able to compile, I would create a pull-request with the instruction for MacOS :).

The error I get during compilation is the following: 
```
c++ -Ilibhdoc.a.p -I. -I.. -I../src -Isubprojects/zlib-1.2.13 -I../subprojects/zlib-1.2.13 -I../subprojects/rapidjson-27c3a8dc0e2c9218fe94986d249a12b5ed838f1d/include -Isubprojects/cmark-gfm-0.29.0.gfm.6 -I../subprojects/cmark-gfm-0.29.0.gfm.6 -I../subprojects/cmark-gfm-0.29.0.gfm.6/src -I../subprojects/cmark-gfm-0.29.0.gfm.6/extensions -I../subprojects/spdlog-1.9.2/include -Isubprojects/ctml -I../subprojects/ctml -I../subprojects/argparse-2.9/include -Isubprojects/tomlplusplus-3.2.0/include -I../subprojects/tomlplusplus-3.2.0/include -I../subprojects/doctest-2.4.9/doctest -Isubprojects/cpp-httplib-0.11.2 -I../subprojects/cpp-httplib-0.11.2 -I/usr/local/Cellar/openssl@3/3.1.0/include -fcolor-diagnostics -Wall -Winvalid-pch -Wextra -Wpedantic -std=c++20 -O0 -g -fno-rtti -DRAPIDJSON_HAS_STDSTRING -DCPPHTTPLIB_OPENSSL_SUPPORT -DCPPHTTPLIB_ZLIB_SUPPORT -isystem/usr/local/opt/llvm/include -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -MD -MQ libhdoc.a.p/src_frontend_Frontend.cpp.o -MF libhdoc.a.p/src_frontend_Frontend.cpp.o.d -o libhdoc.a.p/src_frontend_Frontend.cpp.o -c ../src/frontend/Frontend.cpp
../src/frontend/Frontend.cpp:154:35: error: expected '(' for function-style cast or type construction
    llvm::Optional<llvm::StringRef>    redirects[]   = {llvm::None, {"/dev/null"}, {tempFile}}; // stdin, stdout, stderr
                   ~~~~~~~~~~~~~~~^
../src/frontend/Frontend.cpp:154:11: error: no member named 'Optional' in namespace 'llvm'
    llvm::Optional<llvm::StringRef>    redirects[]   = {llvm::None, {"/dev/null"}, {tempFile}}; // stdin, stdout, stderr
    ~~~~~~^
../src/frontend/Frontend.cpp:154:50: error: expected expression
    llvm::Optional<llvm::StringRef>    redirects[]   = {llvm::None, {"/dev/null"}, {tempFile}}; // stdin, stdout, stderr
                                                 ^
../src/frontend/Frontend.cpp:154:40: error: use of undeclared identifier 'redirects'
    llvm::Optional<llvm::StringRef>    redirects[]   = {llvm::None, {"/dev/null"}, {tempFile}}; // stdin, stdout, stderr
                                       ^
../src/frontend/Frontend.cpp:154:63: error: no member named 'None' in namespace 'llvm'; did you mean 'move'?
    llvm::Optional<llvm::StringRef>    redirects[]   = {llvm::None, {"/dev/null"}, {tempFile}}; // stdin, stdout, stderr
                                                        ~~~~~~^~~~
                                                              move
/usr/local/opt/llvm/include/llvm/ADT/STLExtras.h:1862:10: note: 'move' declared here
OutputIt move(R &&Range, OutputIt Out) {
         ^
../src/frontend/Frontend.cpp:157:81: error: no member named 'None' in namespace 'llvm'
    int rc = llvm::sys::ExecuteAndWait(compilerPath.get(), compilerFlags, llvm::None, redirects, 10, 0, &errMsg);
                                                                          ~~~~~~^
../src/frontend/Frontend.cpp:157:87: error: use of undeclared identifier 'redirects'
    int rc = llvm::sys::ExecuteAndWait(compilerPath.get(), compilerFlags, llvm::None, redirects, 10, 0, &errMsg);
                                                                                      ^
7 errors generated.
```

Attached the logs of the `meson build` and of the `ninja -C build`. Let me know if you would need any more details.

Thank you again!
Riccardo

EDIT:
I can compile hdoc on a clean ubuntu machine. However, it would be nice to know the reason for the issue on the macOS... if you have any idea :)

[meson-build.log](https://github.com/hdoc/hdoc/files/11401767/meson-build.log)
[ninja.log](https://github.com/hdoc/hdoc/files/11401768/ninja.log)

**Comment by hdoc** [comment]
Thank you for the kind words :)

I can see from the meson-build.log file you shared that you're using LLVM 16:
```
Run-time dependency LLVM found: YES 16.0.3
```

From what I can see, it looks like there are some breaking changes in LLVM 16 which cause hdoc's compilation to fail. Namely the type `LLVM::None` has been deprecated. hdoc is currently using LLVM 14 internally and we will upgrade to a newer version of LLVM in an upcoming release. 

The Ubuntu build likely works because you're using an older version of LLVM which is compatible with hdoc. I would advise that you downgrade the version of LLVM on your Mac to a supported version. Otherwise it looks like the breaking changes are quite minimal (use `std::nullopt` instead of `llvm::None`) so if you're willing to contribute a PR we'd happily accept it.

Thank you

**Comment by grhawk** [comment]
Thank you very much for your swift reply. I will try to have a look into it! :)
