### ISSUE TITLE
Output Markdown instead of HTML

### ISSUE THREAD

**Issue by jcurtis-cc** [hdoc/hdoc#46]
The HTML generated is lovely and [integrates well](https://hdoc.io/docs/features/markdown-pages/) with existing markdown - however it would be nice to generate everything in pure markdown instead of HTML. Is this either in flight or planned?

I'm currently using `pandoc` to convert the static HTML to markdown - but there's a fair bit that doesn't translate particularly well.

**Comment by hdoc** [comment]
Unfortunately we're not planning on adding Markdown as an output format besides the existing HTML. We have [a JSON output option](https://hdoc.io/docs/reference/config-file-reference/#dump-json-payload) that contains all of the information available in the HTML as a structured JSON document. If you really want Markdown, it should be possible to grab the information you want out of that JSON and produce Markdown files with a templating engine and some glue code.
