### ISSUE TITLE
Deleting account

### ISSUE THREAD

**Issue by skifli** [hdoc/hdoc#50]
Hi, I'm trying to delete my account but I don't see an option to do so in my account's settings. Where should I do this?

Thanks.

**Comment by hdoc** [comment]
Hello, can you please send an email to contact@hdoc.io with your account username so that I can queue it up for deletion? We don't currently have a way for users to delete their accounts (this is on the roadmap) so for now it has to be manual. I apologize for the inconvenience.

**Comment by skifli** [comment]
I'll do that, thanks.
